export const blogCategories = [
  "Estructuras metálicas",
  "Ingeniería y diseño",
  "Calidad y mantenimiento",
];

export const blogPosts = [
  {
    slug: "cuando-una-estructura-metalica-requiere-evaluacion-reforzamiento-o-reemplazo",
    title: "Cuándo una estructura metálica requiere evaluación, reforzamiento o reemplazo",
    excerpt: "Nuevas cargas, corrosión, deformaciones o reparaciones no documentadas pueden cambiar la condición de una estructura. Evaluar permite decidir con evidencia, no por apariencia.",
    image: "/assets/images/blog/evaluacion-estructura.webp",
    imageAlt: "Evaluación técnica de una torre metálica existente",
    categories: ["Estructuras metálicas", "Ingeniería y diseño", "Calidad y mantenimiento"],
    date: "2026-08-03",
    essentials: ["Señales: daño, modificación, nueva carga o falta de documentos.", "Proceso: inspeccionar, medir, modelar y verificar.", "Decisión: mantener, reparar, reforzar, restringir o reemplazar."],
    sections: [
      ["Cuándo debe evaluarse", "La incorporación de antenas, plataformas, soportes, cables o equipos puede alterar la demanda original. También justifican una revisión la corrosión, las deformaciones, las fisuras, los pernos faltantes, los asentamientos y los eventos extraordinarios. Una pieza aparentemente liviana puede ser relevante cuando tiene gran área expuesta o se instala lejos del eje."],
      ["Inspección no es lo mismo que evaluación", "La inspección registra el estado visible y los hallazgos. La evaluación integra esa información con geometría, materiales, cargas, pérdidas de sección, uniones, cimentación y análisis. Una fotografía puede señalar una anomalía; el cálculo permite estimar su efecto dentro del sistema."],
      ["Recopilación y levantamiento", "Planos, memorias, certificados, mantenimientos, modificaciones e inventarios previos deben compararse con la condición real. En campo pueden revisarse perfiles, espesores, soldaduras, pernos, verticalidad, tensores, cimentación visible, drenajes, recubrimientos y equipos instalados. Los ensayos se seleccionan según los hallazgos."],
      ["Inventario y modelo de cargas", "El propietario debe validar equipo, peso, dimensión, área expuesta, cota, orientación, excentricidad, soporte y condición futura. El modelo debe representar la geometría y el estado existente, no únicamente el diseño original."],
      ["Análisis estructural", "La evaluación y el análisis estructural pueden recomendar continuar operando, ejecutar mantenimiento, reparar, reforzar, restringir el uso o reemplazar. El reforzamiento aumenta o recupera capacidad; la reparación corrige una condición deteriorada. No son conceptos equivalentes."],
      ["Enfoque de ingeniería y toma de decisiones", "El reemplazo puede resultar más razonable cuando el deterioro es extenso, la geometría dificulta la intervención, la cimentación es insuficiente o el costo y riesgo del reforzamiento se aproximan a una solución nueva."],
      ["Conclusión", "La decisión correcta se construye con información verificable. Definir el alcance de inspección y evaluación antes de intervenir permite reducir incertidumbre y escoger una solución proporcionada al estado real de la estructura."],
    ],
  },
  {
    slug: "como-seleccionar-un-poste-metalico-segun-su-aplicacion",
    sourceSlug: "como-seleccionar-un-poste-metalico-segun-su-aplicacion-un-poste-no-debe-seleccionarse-solo-por-altura-o-diametro-la-funcion-los-equipos-el-viento-la-excentricidad-la-union-la-cimentacion-y-el-montaje",
    title: "Cómo seleccionar un poste metálico según su aplicación",
    excerpt: "Un poste no debe seleccionarse solo por altura o diámetro. La función, los equipos, el viento, la excentricidad, la unión, arquitectura, la cimentación y el montaje gobiernan la solución.",
    image: "/assets/images/blog/poste-metalico.webp",
    imageAlt: "Ingenieros seleccionando postes metálicos para una instalación",
    categories: ["Estructuras metálicas", "Ingeniería y diseño"],
    date: "2026-08-03",
    essentials: ["Aplicación: define desempeño, acceso y mantenimiento.", "Carga: peso, superficie, altura y excentricidad.", "Configuración: geometría, unión, protección y cimentación."],
    sections: [
      ["Definir la aplicación", "Telecomunicaciones, videovigilancia, iluminación, señalización, energía, protección atmosférica o instrumentación requieren condiciones diferentes. La función define el equipo, el acceso, la deformación admisible y las consecuencias de una interrupción."],
      ["Equipos y accesorios", "El requerimiento debe registrar peso, dimensiones, área expuesta, cota, orientación, excentricidad, soportes, cables y crecimiento futuro. Un equipo montado sobre un brazo produce efectos distintos a otro colocado sobre el eje."],
      ["Viento y condiciones del lugar", "El viento actúa sobre el cuerpo del poste y sobre cada antena, cámara, luminaria, panel, cable o accesorio. Ubicación, altura, topografía y exposición deben definirse para el proyecto real."],
      ["Geometría y fabricación", "Los postes circulares ofrecen una sección continua. Los octogonales o hexagonales se obtienen por plegado y requieren controlar caras, conicidad, costura, bridas y orientación de accesorios. La elección debe considerar disponibilidad de material, fabricación, cargas, conexión, transporte y apariencia."],
      ["Una pieza o seccionado", "Una sola pieza reduce uniones, pero puede limitar transporte y galvanizado. Los postes seccionados facilitan logística e izaje, aunque incorporan empalmes que deben diseñarse y controlarse. Un traslape no debe definirse mediante una regla universal; depende de la geometría, cargas, tolerancias y método de montaje."],
      ["Placa base y cimentación", "Placa, cartelas, pernos, plantilla, nivelación y grout deben coordinarse con las reacciones y el terreno. El galvanizado o sistema de pintura debe responder al ambiente y prever drenaje, ventilación y mantenimiento."],
    ],
  },
  {
    slug: "que-debe-contener-una-memoria-de-calculo-estructural-para-ser-util-y-verificable",
    title: "Qué debe contener una memoria de cálculo estructural para ser útil y verificable",
    excerpt: "Una memoria no es una colección de capturas de software. Debe explicar los datos, criterios, modelo, verificaciones, resultados y límites que sustentan la solución.",
    image: "/assets/images/blog/memoria-calculo.webp",
    imageAlt: "Desarrollo y revisión de una memoria de cálculo estructural",
    categories: ["Ingeniería y diseño", "Estructuras metálicas"],
    date: "2026-08-03",
    essentials: ["Propósito: explicar y sustentar la decisión estructural.", "Verificación: permitir que otro profesional siga el razonamiento.", "Coordinación: conectar memoria, planos, fabricación y cimentación."],
    sections: [
      ["Qué es una memoria de cálculo", "Es el documento que conecta requerimiento, datos de entrada, normas, hipótesis, modelo, cargas, análisis, verificaciones, resultados y planos. El software facilita el cálculo, pero no reemplaza el criterio. Una salida numérica sin explicación no demuestra que la estructura haya sido representada correctamente."],
      ["Identificación, alcance y revisiones", "La portada debe identificar proyecto, ubicación, estructura, código, revisión, fecha y responsables. El historial de cambios permite saber qué versión está vigente. También debe declarar qué comprende y qué excluye: superestructura, uniones, placa base, pernos, cimentación, equipos, montaje o evaluación de una estructura existente."],
      ["Normas y criterios", "Se deben indicar norma, edición, método de diseño, criterios contractuales y jerarquía aplicable. Frases como “según normas internacionales” son insuficientes. Ubicación, uso, importancia, dimensiones, materiales, equipos, apoyos, suelo, ambiente y límites de servicio deben quedar registrados. Los supuestos deben ser visibles."],
      ["Cargas, combinaciones y modelo", "La memoria debe explicar peso propio, equipos, accesorios, mantenimiento, viento, sismo y otras acciones pertinentes, así como su posición y excentricidad. También debe describir software, tipo de elementos, apoyos, liberaciones, rigideces, no linealidad, segundo orden y validaciones efectuadas."],
      ["Verificaciones y resultados", "Los resultados deben identificar elementos y combinaciones gobernantes, resistencia, estabilidad, uniones, desplazamientos, rotaciones y reacciones. Un ratio aislado sin contexto no es suficiente."],
      ["Compatibilidad con el diseño de cimentación", "Las reacciones, geometría de apoyo, pernos, placa base, cotas y condiciones de rigidez deben llegar al diseñador de cimentaciones. Los planos deben corresponder a la misma revisión de la memoria."],
    ],
  },
  {
    slug: "control-de-calidad-en-estructuras-metalicas-que-revisar-antes-del-despacho",
    title: "Control de calidad en estructuras metálicas: qué revisar antes del despacho",
    excerpt: "Los problemas detectados durante el montaje cuestan más que los corregidos en taller. La calidad debe acompañar el proyecto desde los planos hasta el embalaje.",
    image: "/assets/images/blog/control-calidad.webp",
    imageAlt: "Control dimensional de estructuras metálicas antes del despacho",
    categories: ["Calidad y mantenimiento", "Estructuras metálicas"],
    date: "2026-08-03",
    essentials: ["Prevención: detectar incompatibilidades antes de la obra.", "Evidencia: respaldar la conformidad con registros.", "Resultado: menos retrabajos, paradas y reclamos."],
    sections: [
      ["La calidad empieza antes de cortar", "La primera inspección debe ser documental. Planos aprobados, revisiones vigentes, materiales, tolerancias, uniones y sistema de protección superficial deben estar definidos antes de liberar el trabajo. Fabricar con una revisión antigua puede producir piezas bien ejecutadas, pero equivocadas para el proyecto."],
      ["Materiales y trazabilidad", "Los certificados, lotes, marcas, recepción y relación entre material y pieza permiten demostrar qué acero fue utilizado. El nivel de trazabilidad depende de la criticidad y del contrato, pero nunca debería perderse durante el proceso."],
      ["Corte, perforado y armado", "Se controlan longitudes, geometría, diámetros y posición de agujeros, biseles, identificación, alineamiento y preparación de juntas. Las correcciones improvisadas en obra deben evitarse."],
      ["Soldadura", "El control comprende procedimiento, calificación, preparación, consumibles, condiciones ambientales, ejecución, limpieza e inspección. Los ensayos adicionales se definen según el tipo de unión y la especificación contractual."],
      ["Control dimensional y prearmado", "Una estructura puede tener soldaduras aceptables, pero eso no garantiza el ensamblaje en campo. Para asegurar el montaje preciso, se comprueban en taller longitudes, diagonales, verticalidad, alineación de bridas, perforaciones y la interconexión entre módulos antes del galvanizado y despacho."],
      ["Protección superficial y despacho", "El galvanizado exige ventilación, drenaje y control de deformación. La pintura requiere preparación, condiciones ambientales, compatibilidad y espesor. Antes de despachar se verifican cantidades, marcación, accesorios, protección, estabilidad para transporte, lista de piezas y documentación final."],
    ],
  },
  {
    slug: "proteccion-contra-rayos-en-instalaciones-industriales-como-definir-el-sistema-adecuado",
    sourceSlug: "proteccion-contra-rayos-en-instalaciones-industriales-como-definir-el-sistema-adecuado-un-sistema-de-proteccion-no-se-limita-a-instalar-un-captor-debe-coordinar-captacion-bajantes-puesta-a-tierra-equi",
    title: "Protección contra rayos en instalaciones industriales: cómo definir el sistema adecuado",
    excerpt: "Un sistema de protección no se limita a instalar un captor. Debe coordinar captación, bajantes, puesta a tierra, equipotencialidad y seguridad contra sobretensiones.",
    image: "/assets/images/blog/proteccion-rayos.webp",
    imageAlt: "Sistema de protección contra rayos en una instalación industrial",
    categories: ["Ingeniería y diseño", "Calidad y mantenimiento"],
    date: "2026-08-03",
    essentials: ["Riesgo: personas, estructura, equipos y continuidad.", "Sistema: protección externa e interna coordinadas.", "Criterio: seleccionar desde la evaluación, no desde el producto."],
    sections: [
      ["Primero debe entenderse el riesgo", "Una descarga puede producir daño físico, incendio, tensiones peligrosas, fallas de tableros, pérdida de comunicaciones o interrupción de procesos. Las consecuencias dependen del uso de la instalación y de su criticidad. Por eso, la selección no debe comenzar con la compra de un captor, sino con la evaluación de la estructura, las personas, los servicios entrantes y los equipos sensibles."],
      ["Sistema de captación", "Su función es interceptar la descarga en puntos previstos. La disposición debe responder al método de diseño adoptado y a la geometría real de la instalación. No basta con comparar radios promocionales."],
      ["Conductores de bajada", "Conducen la corriente hacia tierra. Su cantidad, recorrido, continuidad, fijación y separación respecto de otros elementos deben coordinarse para reducir rutas no controladas y diferencias de potencial."],
      ["Puesta a tierra y equipotencialidad", "La puesta a tierra facilita la dispersión de la corriente. Su configuración depende de la resistividad, el espacio disponible, la corrosividad y las redes existentes. La equipotencialidad vincula masas, estructuras, tuberías y sistemas para limitar diferencias peligrosas. Un valor aislado de resistencia no describe por sí solo el desempeño del sistema."],
      ["Protección contra sobretensiones", "Las sobretensiones pueden ingresar por energía, telecomunicaciones, control o instrumentación. Los dispositivos deben seleccionarse y coordinarse según el sistema eléctrico y los equipos conectados."],
      ["Inspección y mantenimiento", "El diseño debe permitir revisar conexiones, continuidad, corrosión, estado de electrodos, cajas de inspección y protectores contra sobretensiones. También debe existir un registro después de modificaciones o eventos importantes."],
    ],
  },
  {
    slug: "como-elegir-una-torre-de-telecomunicaciones-7-datos-que-deben-definirse-antes-de-cotizar",
    title: "Cómo elegir una torre de telecomunicaciones: 7 datos que deben definirse antes de cotizar",
    excerpt: "La altura es solo el punto de partida. Los equipos, el viento, la ubicación, el terreno, la cimentación y el montaje pueden cambiar por completo la solución adecuada.",
    image: "/assets/images/blog/torre-telecomunicaciones.webp",
    imageAlt: "Inspección de una torre de telecomunicaciones y sus equipos",
    categories: ["Estructuras metálicas", "Ingeniería y diseño"],
    date: "2026-08-03",
    essentials: ["Objetivo: preparar un requerimiento técnicamente completo.", "Resultado: propuestas comparables y menos cambios posteriores.", "Decisión clave: evaluar el sistema completo, no solo la altura."],
    sections: [
      ["La altura no define la torre", "Dos torres de 30 metros pueden tener exigencias completamente distintas. Una puede soportar una antena liviana en un entorno urbano protegido y otra recibir múltiples equipos en una zona elevada, abierta y con acceso limitado. La solución debe responder a la operación, las acciones ambientales, las cargas presentes y futuras, la cimentación, el transporte y el nivel de documentación que el proyecto necesita."],
      ["Definir el uso y la importancia", "Antes de elegir una configuración conviene establecer qué servicio prestará la estructura, cuán crítica es la continuidad de la operación, con qué frecuencia se accederá a ella y si existen ampliaciones previstas. La consecuencia de una interrupción también importa: una torre para conectividad interna no se evalúa igual que una infraestructura para una operación minera, una red crítica o un sistema de emergencia."],
      ["Preparar un inventario real de equipos", "El inventario debe registrar tipo, cantidad, peso, dimensiones, área expuesta, cota de instalación, orientación, excentricidad, soporte requerido y cableado asociado. No es recomendable resumir todo como “carga en la cima” cuando existen equipos en diferentes niveles o elementos que trabajan fuera del eje."],
      ["Identificar correctamente el emplazamiento", "Ubicación, altitud, topografía, exposición, ambiente corrosivo, accesos y restricciones logísticas son datos de diseño. La velocidad de viento no debe copiarse de otro proyecto sin validar la norma y las condiciones del lugar."],
      ["Comparar la solución completa", "Una torre autosoportada ocupa menos área de anclajes y concentra la infraestructura. Una torre ventada puede ser eficiente cuando existe terreno suficiente y se puede controlar el estado de tensores y anclajes. La alternativa con menos acero no siempre tiene el menor costo total: deben sumarse cimentaciones, ocupación del terreno, montaje, inspección y mantenimiento."],
      ["Integrar terreno, cimentación y montaje", "La torre y su cimentación trabajan como un sistema. El estudio de suelos, las reacciones de la superestructura, la placa base, los pernos y la secuencia de montaje deben coordinarse antes de fabricar. También deben revisarse longitudes transportables, peso de módulos, capacidad operativa, restricciones de acceso y clima esperado durante el izaje."],
    ],
  },
];

export const getBlogPost = (slug) =>
  blogPosts.find((post) => post.slug === slug || post.sourceSlug === slug) || blogPosts[0];

export const getPostUrl = (post) => `/blog/post/?slug=${encodeURIComponent(post.slug)}`;
